<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { liveQuery } from 'dexie';
import { db, categories, companions, companionImage, day, uid, saveTask, completeTask, saveOrder, moveToday, exportBackup, validateBackup, restoreBackup, type Task, type Profile, type Session, type Backup } from './data';
import { focus, startFocus, pauseFocus, resumeFocus, finishFocus, hydrateFocus } from './focus';
import Planner from './Planner.vue';
import Rewards from './Rewards.vue';
import OfflineStatus from './OfflineStatus.vue';
import { registerUpdateGuard } from './update-safety';
import GrowthProgress from './GrowthProgress.vue';
import { maintainProgress, setTaskPaused } from './progression';
const route=useRoute(),router=useRouter();
const page=computed(()=>route.path==='/'?'today':route.path.slice(1));
const profile=ref<Profile>(),tasks=ref<Task[]>([]),sessions=ref<Session[]>([]),segments=ref<{date:string;ms:number}[]>([]),balance=ref(0),loaded=ref(false),error=ref(''),toast=ref(''),busy=ref(false),order=ref({ids:[] as string[],revision:0}),today=ref(day());
const nickname=ref(''),grade=ref<Profile['grade']>('一年级'),companion=ref<Profile['companion']>('tuantuan');
const currentStage=ref(1);
const modal=ref(''),editing=ref<Task>(),selected=ref<Task>(),filter=ref('全部'),range=ref('周'),offset=ref(0),sortIds=ref<string[]>([]),sortRevision=ref(0),chooseTab=ref('之前的安排'),result=ref<'done'|'partial'>('done'),note=ref(''),mood=ref(''),backup=ref<Backup>(),backedUp=ref(false),confirmedSaved=ref(false),mode=ref<'countdown'|'up'>('countdown');
const removeUpdateGuard=registerUpdateGuard(()=>busy.value||!!modal.value);onUnmounted(removeUpdateGuard);
const form=ref({name:'',category:'习惯' as Task['category'],date:day(),criteria:'',minutes:15,stars:1});
const iconNames:Record<string,string>={'习惯':'House','兴趣':'Palette','学习':'BookOpen','成长':'Sprout'};
const pending=computed(()=>tasks.value.filter(t=>t.date===today.value&&['todo','started'].includes(t.status)).sort((a,b)=>{const ia=order.value.ids.indexOf(a.id),ib=order.value.ids.indexOf(b.id);return (ia<0?9999:ia)-(ib<0?9999:ib)||a.createdAt-b.createdAt;}));
const doneToday=computed(()=>tasks.value.filter(t=>t.status==='done'&&t.resultAt&&day(t.resultAt)===today.value));
const earlier=computed(()=>tasks.value.filter(t=>t.date<today.value&&['todo','started'].includes(t.status)));
const todayMinutes=computed(()=>Math.floor(segments.value.filter(s=>s.date===today.value).reduce((a,s)=>a+s.ms,0)/60000));
const currentTask=computed(()=>tasks.value.find(t=>t.id===focus.session?.taskId));
const rangeDates=computed(()=>{if(range.value==='全部')return ['0000-01-01','9999-12-31'];const d=new Date(today.value+'T00:00:00Z');if(range.value==='天'){d.setUTCDate(d.getUTCDate()+offset.value);return [d.toISOString().slice(0,10),d.toISOString().slice(0,10)];}if(range.value==='周'){d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7)+offset.value*7);const end=new Date(d);end.setUTCDate(d.getUTCDate()+6);return[d.toISOString().slice(0,10),end.toISOString().slice(0,10)];}d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+offset.value);const end=new Date(d);end.setUTCMonth(d.getUTCMonth()+1);end.setUTCDate(0);return[d.toISOString().slice(0,10),end.toISOString().slice(0,10)];});
const inRange=(d:string)=>d>=rangeDates.value[0]&&d<=rangeDates.value[1];
const records=computed(()=>tasks.value.filter(t=>t.resultAt&&inRange(day(t.resultAt))).sort((a,b)=>(b.resultAt??0)-(a.resultAt??0)));
const reportSessions=computed(()=>sessions.value.filter(s=>s.endedAt&&inRange(day(s.endedAt))));
const reportMs=computed(()=>segments.value.filter(s=>inRange(s.date)).reduce((n,s)=>n+s.ms,0));
const reportStars=computed(()=>records.value.filter(t=>t.status==='done').reduce((n,t)=>n+(t.locked??t.stars),0));
const trend=computed(()=>{const totals=new Map<string,number>();for(const s of segments.value.filter(s=>inRange(s.date)))totals.set(s.date,(totals.get(s.date)??0)+s.ms);return [...totals].sort().map(([date,ms])=>({date,minutes:Math.floor(ms/60000)}));});
const maxTrend=computed(()=>Math.max(1,...trend.value.map(t=>t.minutes)));
const chosenTasks=computed(()=>tasks.value.filter(t=>chooseTab.value==='已暂停'?t.status==='paused':['todo','started'].includes(t.status)&&(chooseTab.value==='之前的安排'?t.date<today.value:t.date>today.value&&t.date<=day(Date.parse(today.value+'T00:00:00+08:00')+7*86400000))));
const clock=computed(()=>{const s=focus.session;const seconds=Math.max(0,Math.ceil((s?(s.mode==='countdown'?s.targetMs-s.effectiveMs:s.effectiveMs):0)/1000));return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;});
function notify(message:string){toast.value=message;setTimeout(()=>toast.value='',4500);}
async function run(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:'还没保存成功，请再试一次。';}finally{busy.value=false;}}
function go(path:string){modal.value='';error.value='';void router.push('/'+path);}
function newTask(task?:Task){editing.value=task;form.value=task?{name:task.name,category:task.category,date:task.date,criteria:task.criteria,minutes:task.minutes,stars:task.stars}:{name:'',category:'习惯',date:today.value,criteria:'',minutes:15,stars:1};modal.value='task';}
async function submitTask(){await run(async()=>{await saveTask({...editing.value,...form.value,id:editing.value?.id??uid(),status:editing.value?.status??'todo',createdAt:editing.value?.createdAt??Date.now()});modal.value='';notify('已经安排到 '+form.value.date);});}
function checkTask(task:Task){selected.value=task;result.value='done';note.value='';mood.value='';modal.value='complete';}
async function submitResult(){await run(async()=>{const task=selected.value!;if(focus.session?.taskId===task.id)await pauseFocus('准备记录结果');await completeTask(task.id,result.value,note.value,mood.value);if(focus.session?.taskId===task.id)focus.session=null;modal.value='';notify(result.value==='done'?`已经记好啦！获得 ${task.locked??task.stars} 颗星星`:'这一部分努力，已经记好啦');if(page.value==='focus')go('today');});}
function download(data:string,name:string,type:string){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function saveBackup(){await run(async()=>{if(focus.session)await pauseFocus('导出备份');download(JSON.stringify(await exportBackup(),null,2),'成长森林-'+day()+'.json','application/json');backedUp.value=true;notify('备份文件已生成，请确认文件已保存。');});}
async function loadBackup(event:Event){await run(async()=>{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>20*1024*1024)throw Error('备份文件太大，请选择20MB以内的文件');backup.value=validateBackup(JSON.parse(await file.text()));backedUp.value=!profile.value;confirmedSaved.value=!profile.value;modal.value='import';});(event.target as HTMLInputElement).value='';}
async function applyBackup(){await run(async()=>{if(!backedUp.value||!confirmedSaved.value)throw Error('请先保存当前备份并确认');if(focus.session)await pauseFocus('恢复备份');await restoreBackup(backup.value);await maintainProgress();await hydrateFocus();modal.value='';go('today');notify('备份已经恢复');});}
async function createProfile(){await run(async()=>{if(!nickname.value.trim())throw Error('先告诉我怎么称呼你吧');await db.profiles.put({id:'student',nickname:nickname.value.trim(),grade:grade.value,companion:companion.value,reduceMotion:false});go('today');});}
function begin(task:Task){selected.value=task;modal.value='start';}
function startSort(){sortIds.value=pending.value.map(t=>t.id);sortRevision.value=order.value.revision;modal.value='sort';}
function shift(index:number,delta:number){const ids=[...sortIds.value];[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];sortIds.value=ids;}
function exportCsv(){const cell=(s:unknown)=>'"'+String(s).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';download('\uFEFF'+[['任务','方向','安排日期','结果','实际完成日期','获得星星'],...records.value.map(t=>[t.name,t.category,t.date,t.status==='done'?'完成':'部分完成',day(t.resultAt),t.status==='done'?(t.locked??t.stars):0])].map(row=>row.map(cell).join(',')).join('\r\n'),'成长记录-'+day()+'.csv','text/csv;charset=utf-8');}
watch(range,()=>offset.value=0);
let returnFocus:HTMLElement|null=null;
watch(modal,async value=>{error.value='';if(value){returnFocus=document.activeElement as HTMLElement;await nextTick();document.querySelector<HTMLElement>('.modal input:not([type=radio]),.modal button')?.focus();document.body.style.overflow='hidden';}else{document.body.style.overflow='';returnFocus?.focus();}});
function trapFocus(event:KeyboardEvent){if(!modal.value||event.key!=='Tab')return;const nodes=[...document.querySelectorAll<HTMLElement>('.modal button:not(:disabled),.modal input:not(:disabled),.modal select,.modal textarea')].filter(el=>el.offsetParent!==null);const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}
watch(()=>profile.value?.reduceMotion,v=>document.documentElement.classList.toggle('reduced-motion',!!v));
const subscription=liveQuery(async()=>({profile:await db.profiles.get('student'),tasks:await db.tasks.toArray(),sessions:await db.sessions.toArray(),segments:await db.segments.toArray(),ledger:await db.ledger.toArray(),order:await db.orders.get(day()),journeys:await db.journeys.toArray()})).subscribe({next:data=>{profile.value=data.profile;tasks.value=data.tasks;sessions.value=data.sessions;segments.value=data.segments;balance.value=data.ledger.reduce((n,l)=>n+l.delta,0);order.value=data.order??{ids:[],revision:0};currentStage.value=data.journeys.filter(j=>j.companionId===data.profile?.companion).sort((a,b)=>b.startedAt-a.startedAt)[0]?.stage??1;loaded.value=true;},error:e=>{error.value='无法打开本地记录：'+e;loaded.value=true;}});
let dayTimer:ReturnType<typeof setInterval>;
function refreshProgress(){void maintainProgress().catch(e=>error.value='成长安排尚未更新：'+(e instanceof Error?e.message:String(e)));}
function onVisible(){if(!document.hidden){today.value=day();refreshProgress();}}
watch(()=>profile.value?.id,(value,old)=>{if(value&&!old)refreshProgress();});
watch(today,refreshProgress);
onMounted(()=>{void hydrateFocus();refreshProgress();document.addEventListener('visibilitychange',onVisible);document.addEventListener('keydown',trapFocus);dayTimer=setInterval(()=>today.value=day(),30000);});
onUnmounted(()=>{subscription.unsubscribe();clearInterval(dayTimer);document.removeEventListener('keydown',trapFocus);document.removeEventListener('visibilitychange',onVisible);});
</script>

<template>
 <div class="app-shell" :class="{ 'focus-shell':page==='focus' }">
  <header class="topbar"><a href="#/today" class="brand"><img src="./assets/app-icon.webp" alt="">成长森林<span>GrowBuddy</span></a><button v-if="profile" class="quiet" @click="go('settings')"><img src="./assets/icons/Settings.svg" alt="">设置</button></header>
  <OfflineStatus :details="page==='settings'" />
  <p v-if="error&&!modal" class="error" role="alert">{{error}}</p>
  <p v-if="focus.error" class="error" role="alert">{{focus.error}}</p>
  <main v-if="!loaded" class="empty">正在打开你的成长记录…</main>
  <main v-else-if="!profile" class="welcome">
   <div class="eyebrow">我的成长，从这里开始</div><h1>你好，欢迎来到成长森林</h1><p class="muted">选一位小伙伴，陪你每天进步一点点。</p>
   <form class="panel welcome-form" @submit.prevent="createProfile"><div class="two-col"><label>怎么称呼你？<input v-model="nickname" required maxlength="20" placeholder="输入我的昵称" autocomplete="nickname"></label><label>我在读<select v-model="grade"><option>一年级</option><option>二年级</option><option>三年级</option></select></label></div>
    <fieldset><legend>选一位陪伴我的伙伴</legend><div class="companion-grid"><label v-for="c in companions" :key="c[0]" class="companion-option" :class="{selected:companion===c[0]}"><input v-model="companion" type="radio" :value="c[0]" name="companion"><img :src="companionImage(c[0]!)" :alt="c[2]"><strong>{{c[1]}}</strong></label></div></fieldset>
    <button class="primary wide" :disabled="busy">一起出发</button><p class="small muted">记录保存在这台设备的浏览器里，记得定期备份。</p><label class="file-button">我有备份，导入记录<input type="file" accept="application/json,.json" @change="loadBackup"></label>
   </form>
  </main>
  <main v-else-if="page==='today'">
   <section class="page-heading storybook-heading"><div><div class="eyebrow">每天进步一点点</div><h1>今日行动</h1><p class="muted">{{new Date(today+'T12:00:00+08:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}}</p></div><div class="hello"><span>{{profile.nickname}}，<br>今天先做哪件事？</span><img :src="companionImage(profile.companion,currentStage)" :alt="companions.find(c=>c[0]===profile?.companion)?.[1]"></div></section>
   <div class="daily-summary"><div><span class="round-icon"><img src="./assets/icons/Sprout.svg" alt=""></span><div><strong>已完成 {{doneToday.length}} 件</strong><span>每一步努力，都有意义</span></div></div><div><span class="round-icon"><img src="./assets/icons/Clock.svg" alt=""></span><div><strong>专注 {{todayMinutes}} 分钟</strong><span>一次专心做一件事</span></div></div></div>
   <button v-if="focus.session" class="session-banner" @click="go('focus')">{{focus.session.status==='running'?'正在专注':'专注已暂停'}} · {{currentTask?.name}}<span>回到专注 →</span></button>
   <div class="section-heading today-toolbar"><h2>接下来做什么？</h2><div class="actions"><button class="secondary" @click="modal='choose'"><img src="./assets/icons/ListChecks.svg" alt="">选择任务</button><button class="quiet" :disabled="pending.length<2" @click="startSort"><img src="./assets/icons/ArrowUpDown.svg" alt="">调整顺序</button></div></div>
   <section v-if="!pending.length" class="panel empty"><img src="./assets/empty-records.webp" alt="" class="empty-art"><h2>{{doneToday.length?'今天的安排都完成啦':'今天想做点什么？'}}</h2><p class="muted">{{doneToday.length?'可以休息一下，也可以探索新的安排。':'去探索发现，安排一件自己想做的事吧。'}}</p><button class="primary" @click="go('explore')">去探索发现安排</button></section>
   <article v-for="(task,index) in pending" :key="task.id" class="panel task-card" :class="{featured:index===0}"><div class="task-content"><div class="category-tile" :class="'cat-'+task.category"><img :src="'./assets/icons/'+iconNames[task.category]+'.svg'" alt=""></div><div class="task-description"><span v-if="index===0" class="eyebrow">下一件小事</span><h2>{{task.name}}</h2><div class="meta">{{task.category}}<span>◷ {{task.minutes}} 分钟</span><span class="stars">{{(task.locked??task.stars)===0?'无星星奖励':'★ '+(task.locked??task.stars)+' 颗星星'}}</span></div><p>{{task.criteria}}</p></div></div><div class="task-actions"><button class="primary" :disabled="busy||!!focus.session" @click="begin(task)"><img src="./assets/icons/Play.svg" alt="">开始专注</button><button class="secondary" @click="checkTask(task)"><img src="./assets/icons/CircleCheck.svg" alt="">记录完成</button></div></article>
   <details class="panel fold"><summary>已完成 {{doneToday.length}} 件</summary><div v-for="t in doneToday" :key="t.id" class="record-row"><span>✓ {{t.name}}</span><span class="stars">★ {{t.locked??t.stars}}</span></div><p v-if="!doneToday.length" class="muted">完成后，这里会留下你的足迹。</p></details>
   <details class="panel fold"><summary>之前的安排 {{earlier.length}} 件</summary><div v-for="t in earlier" :key="t.id" class="record-row"><div>{{t.name}}<small>{{t.date}}</small></div><button class="secondary" @click="checkTask(t)">记录结果</button></div></details>
  </main>
  <main v-else-if="page==='explore'">
   <section class="page-heading"><div><div class="eyebrow">从一件想做的事开始</div><h1>探索发现</h1><p class="muted">把小小的想法，变成每天的行动。</p></div><button class="primary" @click="newTask()"><img src="./assets/icons/Plus.svg" alt="">创建独立任务</button></section>
   <div class="category-tabs"><button v-for="c in ['全部',...categories]" :key="c" :class="{active:filter===c}" @click="filter=c"><img v-if="iconNames[c]" :src="'./assets/icons/'+iconNames[c]+'.svg'" alt="">{{c}}</button></div>
   <Planner :category="filter" @notice="notify" />
   <div class="section-heading"><h2>我的安排</h2><span class="muted">{{tasks.filter(t=>filter==='全部'||t.category===filter).length}} 项</span></div>
   <section v-if="!tasks.some(t=>filter==='全部'||t.category===filter)" class="panel empty"><img class="empty-art" src="./assets/empty-records.webp" alt=""><h2>让一个小想法发芽</h2><p class="muted">读一段故事、整理书包，或者练习喜欢的事。</p><button class="primary" @click="newTask()">安排我的第一件事</button></section>
   <div class="arrangements"><article v-for="t in tasks.filter(t=>filter==='全部'||t.category===filter)" :key="t.id" class="panel arrangement"><div class="meta"><span class="tag">{{t.category}}</span><span>{{t.date}}</span><span v-if="t.planId">来自计划</span></div><h2>{{t.name}}</h2><p>{{t.criteria}}</p><div class="meta"><span>{{t.minutes}} 分钟</span><span class="stars">★ {{t.locked??t.stars}}</span></div><template v-if="['todo','started','paused'].includes(t.status)"><button class="secondary wide" @click="newTask(t)">查看与编辑</button><button class="quiet" :disabled="busy" @click="run(async()=>{await setTaskPaused(t.id,t.status!=='paused');notify(t.status==='paused'?'安排已恢复':'安排已暂停')})">{{t.status==='paused'?'恢复这项安排':'暂停这项安排'}}</button></template><span class="result-tag">{{({todo:'待完成',started:'已开始',paused:'已暂停',done:'✓ 已完成',partial:'已记录部分完成',ended:'已结束，不再安排'})[t.status]}}</span></article></div>
  </main>
  <main v-else-if="page==='growth'">
   <section class="page-heading growth-heading"><div><div class="eyebrow">每一份努力，都留下了足迹</div><h1>我的成长</h1></div><img class="heading-art" src="./assets/A01.webp" alt=""><div class="balance"><span>当前可用星星</span><strong>★ {{balance}}</strong></div></section>
   <div class="report-controls"><div class="segmented"><button v-for="r in ['天','周','月','全部']" :key="r" :class="{active:range===r}" @click="range=r">{{r}}</button></div><div v-if="range!=='全部'" class="date-controls"><button aria-label="上一区间" @click="offset--">‹</button><span>{{rangeDates[0]}}<template v-if="range!=='天'"> — {{rangeDates[1]}}</template></span><button aria-label="下一区间" :disabled="offset>=0" @click="offset++">›</button></div><span v-else>全部成长记录</span></div>
   <div class="stats"><div class="panel"><img src="./assets/icons/CircleCheck.svg" alt=""><strong>{{records.filter(t=>t.status==='done').length}}<small>件</small></strong><span>实际完成任务</span></div><div class="panel"><img src="./assets/icons/Clock.svg" alt=""><strong>{{Math.floor(reportMs/60000)}}<small>分钟</small></strong><span>累计专注</span></div><div class="panel"><img src="./assets/icons/Star.svg" alt=""><strong>{{reportStars}}<small>颗</small></strong><span>任务获得星星</span></div><div class="panel"><img src="./assets/icons/Timer.svg" alt=""><strong>{{reportSessions.length}}<small>段</small></strong><span>已结束专注</span></div></div>
   <section class="panel chart-panel"><div class="section-heading"><h2>我的专注足迹</h2><span class="muted">按实际专注日期</span></div><div v-if="trend.length" class="chart"><div v-for="t in trend" :key="t.date" class="bar-column"><span>{{t.minutes}} 分</span><div class="bar" :style="{height:Math.max(4,t.minutes/maxTrend*140)+'px'}"></div><small>{{t.date.slice(5)}}</small></div></div><div v-else class="empty compact"><img src="./assets/empty-records.webp" alt="" class="empty-art"><p>从一次行动开始，留下你的成长足迹。</p></div></section>
   <section class="panel"><div class="section-heading"><h2>任务记录</h2><button class="quiet" :disabled="!records.length" @click="exportCsv">导出 CSV</button></div><div v-for="t in records" :key="t.id" class="record-row"><div><strong>{{t.name}}</strong><small>{{day(t.resultAt)}} · {{t.category}} · {{t.status==='done'?'完成了':'做了一部分'}}</small><p v-if="t.note" class="small">{{t.note}}</p></div><span v-if="t.status==='done'" class="stars">★ {{t.locked??t.stars}}</span></div><p v-if="!records.length" class="muted">这个时间里还没有记录。</p></section>
   <section class="panel record-row rewards-link"><img src="./assets/gift-default.webp" alt=""><div><h2>我的奖励</h2><p>用积累的星星，兑换一份小期待。</p></div><button class="primary" @click="go('growth/rewards')">礼品兑换 →</button></section><GrowthProgress :profile="profile" :from="rangeDates[0]!" :to="rangeDates[1]!" />
  </main>
  <Rewards v-else-if="page==='growth/rewards'" :from="rangeDates[0]!" :to="rangeDates[1]!" @back="go('growth')" @notice="notify" /><main v-else-if="page==='focus'" class="focus-page"><button class="quiet" @click="go('today')">‹ 返回今日行动</button><template v-if="focus.session"><span class="eyebrow">{{focus.session.status==='running'?'现在，只做这一件事':'休息一下，准备好了再继续'}}</span><h1>{{currentTask?.name}}</h1><p class="muted">{{currentTask?.criteria}}</p><div class="timer-circle"><span>{{focus.session.status==='paused'?'已暂停':focus.session.mode==='countdown'?'剩余时间':'累计时间'}}</span><strong class="timer">{{clock}}</strong><span>已记录 {{Math.floor(focus.session.effectiveMs/60000)}} 分钟</span></div><p>{{focus.session.reason}}</p><div class="focus-actions"><button v-if="focus.session.status==='running'" class="primary" :disabled="busy" @click="run(()=>pauseFocus())">暂停一下</button><button v-else class="primary" :disabled="busy" @click="run(resumeFocus)">继续专注</button><button class="secondary" :disabled="busy" @click="run(async()=>{await finishFocus();notify('本段专注已保存，任务结果可以另外记录');go('today')})">结束本段</button></div><img class="focus-companion" src="./assets/04-zhizhi.webp" alt="安静陪伴的智智"><p class="small muted">离开浏览器或锁屏会自动暂停，回来后手动继续。</p></template><section v-else class="empty"><h1>这一段专注已结束</h1><p>专注时间已经记录，任务不会自动完成。</p><button class="primary" @click="go('today')">回到今日行动</button></section></main>
  <main v-else-if="page==='settings'"><div class="page-heading settings-heading"><div><div class="eyebrow">照顾好我的成长记录</div><h1>备份与设置</h1></div><img class="settings-art" src="./assets/saved-success.webp" alt=""><button class="quiet" @click="go('today')">返回今日行动</button></div><section class="panel"><h2>我的资料</h2><p>{{profile.nickname}} · {{profile.grade}}</p><label class="checkbox-row"><input type="checkbox" :checked="profile.reduceMotion" @change="run(()=>db.profiles.update('student',{reduceMotion:($event.target as HTMLInputElement).checked}))">减少动效</label><p class="muted small">日期按北京时间记录。</p></section><section class="panel"><h2>给成长记录留一份备份</h2><p>记录保存在这个浏览器里。更换设备或清理浏览器前，请先导出备份。</p><div class="actions"><button class="primary" :disabled="busy" @click="saveBackup"><img src="./assets/icons/Download.svg" alt="">导出完整备份</button><label class="file-button secondary">导入备份<input type="file" accept="application/json,.json" @change="loadBackup"></label></div><p class="small muted">导入会整体替换当前记录。先预览，再确认。</p></section></main>
  <main v-else class="empty"><h1>这条小路还没找到</h1><button class="primary" @click="go('today')">回到今日行动</button></main>
  <nav v-if="profile&&page!=='focus'" class="bottom-nav" aria-label="主导航"><a v-for="n in [['today','House','今日行动'],['explore','Compass','探索发现'],['growth','Sprout','我的成长']]" :key="n[0]" :href="'#/'+n[0]" :class="{active:(page===n[0]||(n[0]==='growth'&&page.startsWith('growth/')))}" :aria-current="(page===n[0]||(n[0]==='growth'&&page.startsWith('growth/')))?'page':undefined"><img :src="'./assets/icons/'+n[1]+'.svg'" alt=""><span>{{n[2]}}</span></a></nav>
  <div v-if="toast" class="toast" role="status">✓ {{toast}}</div>
  <div v-if="modal" class="modal-backdrop" @click.self="!busy&&(modal='')"><section class="modal panel" role="dialog" aria-modal="true" aria-labelledby="modal-title" @keydown.esc="!busy&&(modal='')"><div class="modal-head"><h2 id="modal-title">{{({task:editing?'编辑任务':'创建独立任务',complete:'看看，这件事做得怎么样？',sort:'调整任务顺序',choose:'选择已有任务',start:'准备开始专注',import:'导入备份预览',companion:'选择陪伴我的伙伴'} as Record<string,string>)[modal]}}</h2><button class="icon-button" aria-label="关闭" :disabled="busy" @click="modal=''">×</button></div><p v-if="error" class="error" role="alert">{{error}}</p>
   <form v-if="modal==='task'" @submit.prevent="submitTask"><label>我想做什么<input v-model="form.name" required maxlength="40" placeholder="比如：阅读一段故事"></label><div class="two-col"><label>属于哪个方向<select v-model="form.category"><option v-for="c in categories" :key="c">{{c}}</option></select></label><label>安排在哪一天<input v-model="form.date" required type="date"></label></div><label>做到什么就算完成<textarea v-model="form.criteria" required maxlength="200" placeholder="比如：读完一段，说说最喜欢的情节。"></textarea></label><div class="two-col"><label>预计用时（分钟）<input v-model.number="form.minutes" required type="number" min="1" max="60" step="1"></label><label>完整完成获得星星<input v-model.number="form.stars" :disabled="editing?.locked!==undefined" required type="number" min="0" max="99" step="1"></label></div><p class="small muted">{{editing?.locked!==undefined?'任务已经开始，奖励已锁定为 '+editing.locked+' 颗星星。':'可以设置 0—99 颗星星；部分完成不发星星。'}}</p><button class="primary wide" :disabled="busy">{{busy?'正在保存…':'保存安排'}}</button></form>
   <form v-else-if="modal==='complete'" @submit.prevent="submitResult"><h3>{{selected?.name}}</h3><p class="criteria">完成标准：{{selected?.criteria}}</p><fieldset class="result-options"><label><input v-model="result" type="radio" value="done" name="result">完成了 <span class="stars">★ {{selected?.locked??selected?.stars}}</span></label><label><input v-model="result" type="radio" value="partial" name="result">做了一部分</label></fieldset><label>现在的心情（可以跳过）</label><div class="moods"><button v-for="m in [['happy','开心'],['calm','平静'],['tired','疲惫'],['sad','难过']]" :key="m[0]" type="button" :class="{selected:mood===m[0]}" @click="mood=mood===m[0]?'':m[0]!"><img :src="'./assets/mood-'+m[0]+'.webp'" alt="">{{m[1]}}</button></div><label>留一句话（可以跳过）<textarea v-model="note" maxlength="500" placeholder="今天有什么想记住的？"></textarea></label><button class="primary wide" :disabled="busy">{{busy?'正在保存…':'记好这次努力'}}</button></form>
   <div v-else-if="modal==='start'"><h3>{{selected?.name}}</h3><p>{{selected?.criteria}}</p><div class="segmented"><button :class="{active:mode==='countdown'}" @click="mode='countdown'">倒计时 {{selected?.minutes}} 分钟</button><button :class="{active:mode==='up'}" @click="mode='up'">正计时</button></div><p class="muted">准备好了吗？专注时不用着急。</p><button class="primary wide" :disabled="busy" @click="run(async()=>{await startFocus(selected!.id,mode);go('focus')})">开始专注</button></div>
   <div v-else-if="modal==='sort'"><div v-for="(id,i) in sortIds" :key="id" class="record-row"><span>{{tasks.find(t=>t.id===id)?.name}}</span><div class="actions"><button :disabled="i===0" :aria-label="'上移第'+(i+1)+'项'" @click="shift(i,-1)">↑</button><button :disabled="i===sortIds.length-1" :aria-label="'下移第'+(i+1)+'项'" @click="shift(i,1)">↓</button></div></div><button class="primary wide" :disabled="busy" @click="run(async()=>{await saveOrder([...sortIds],sortRevision);modal='';notify('任务顺序已保存')})">保存顺序</button></div>
   <div v-else-if="modal==='choose'"><div class="segmented"><button v-for="tab in ['之前的安排','接下来7天','已暂停']" :key="tab" :class="{active:chooseTab===tab}" @click="chooseTab=tab">{{tab}}</button></div><div v-for="t in chosenTasks" :key="t.id" class="record-row"><div>{{t.name}}<small>{{t.date}} · {{t.category}}</small></div><button class="secondary" :disabled="busy" @click="run(async()=>{await moveToday(t.id);notify('已安排到今天')})">安排到今天</button></div><p v-if="!chosenTasks.length" class="empty muted">这里暂时没有可选择的安排。</p></div>
   <div v-else-if="modal==='import'&&backup"><p>将恢复 <strong>{{backup.profiles[0]?.nickname??'空档案'}}</strong> 的成长记录</p><dl><dt>备份时间</dt><dd>{{new Date(backup.exportedAt).toLocaleString('zh-CN')}}</dd><dt>任务</dt><dd>{{backup.tasks.length}} 项</dd><dt>目标 / 计划</dt><dd>{{backup.goals.length}} / {{backup.plans.length}} 项</dd><dt>收藏 / 旅程</dt><dd>{{backup.awards.length}} / {{backup.journeys.length}} 项</dd><dt>专注记录</dt><dd>{{backup.sessions.length}} 段</dd><dt>礼品 / 兑换记录</dt><dd>{{backup.prizes.length}} / {{backup.redemptions.length}} 项</dd><dt>图片</dt><dd>{{backup.rewardImages.length}} 张</dd><dt>版本</dt><dd>{{backup.appVersion}}</dd></dl><p class="criteria">确认后，当前浏览器中的记录会被这份备份整体替换。</p><button v-if="profile" class="secondary wide" :disabled="busy" @click="saveBackup">先导出当前档案</button><label v-if="profile" class="checkbox-row"><input v-model="confirmedSaved" :disabled="!backedUp" type="checkbox">我已确认当前备份文件保存好了</label><button class="primary wide" :disabled="busy||!backedUp||!confirmedSaved" @click="applyBackup">确认替换并恢复</button></div>
   <div v-else-if="modal==='companion'"><div class="companion-grid"><label v-for="c in companions" :key="c[0]" class="companion-option" :class="{selected:companion===c[0]}"><input v-model="companion" type="radio" :value="c[0]" name="change-companion"><img :src="companionImage(c[0]!)" :alt="c[2]"><strong>{{c[1]}}</strong></label></div><button class="primary wide" :disabled="busy" @click="run(async()=>{await db.profiles.update('student',{companion});modal='';notify('伙伴已经来到你身边')})">就选这位伙伴</button></div>
  </section></div>
 </div>
</template>
