<script setup lang="ts">
import { registerUpdateGuard } from "./update-safety";
import { ref, computed, onUnmounted, watch, nextTick } from 'vue';
import { liveQuery } from 'dexie';
import { db, day, uid, categories, type Task } from './data';
import { effectiveSchedule, type Goal, type Plan } from './progression-model';
import { saveGoal,savePlan,setGoalPaused,setPlanPaused,completeGoal,completePlan,templates,useTemplate,addDays,occursOn } from './progression';
const props=defineProps<{category:string}>();
const editorElement=ref<HTMLElement>();
const emit=defineEmits<{notice:[message:string]}>();
const goals=ref<Goal[]>([]),plans=ref<Plan[]>([]),tasks=ref<Task[]>([]),tab=ref('我的目标'),editor=ref(''),error=ref(''),busy=ref(false),review=ref<Goal|Plan>(),reviewType=ref<'goal'|'plan'>('plan'),agreed=ref(false),closeRemaining=ref(false);
const goalForm=ref<Goal>(),planForm=ref<Plan>(),effective=ref(day()),template=ref(templates[0]!),start=ref(day()),end=ref(addDays(day(),6)),stars=ref(1);
const templateFrequency=ref<Plan['frequency']>('daily'),templateWeekdays=ref([1,2,3,4,5]);
watch(editor,async value=>{if(value){await nextTick();editorElement.value?.scrollIntoView({block:'start'});editorElement.value?.querySelector<HTMLElement>('input:not([type=radio]),textarea,select')?.focus({preventScroll:true});}});
const sub=liveQuery(async()=>({goals:await db.goals.toArray(),plans:await db.plans.toArray(),tasks:await db.tasks.toArray()})).subscribe({next:d=>{goals.value=d.goals;plans.value=d.plans;tasks.value=d.tasks;},error:e=>error.value=String(e)});onUnmounted(()=>sub.unsubscribe());
const filteredGoals=computed(()=>goals.value.filter(g=>props.category==='全部'||g.category===props.category));
const filteredPlans=computed(()=>plans.value.filter(p=>props.category==='全部'||p.category===props.category));
const preview=computed(()=>{const draft=planForm.value;if(!draft)return [];const saved=plans.value.find(p=>p.id===draft.id);return Array.from({length:7},(_,i)=>addDays(day(),i)).filter(date=>occursOn(saved&&date<effective.value?effectiveSchedule(saved,date):draft,date));});
const templatePreview=computed(()=>Array.from({length:7},(_,i)=>addDays(day(),i)).filter(date=>occursOn({startDate:start.value,endDate:end.value,frequency:templateFrequency.value,weekdays:templateWeekdays.value},date)));
const affected=computed(()=>planForm.value?tasks.value.filter(t=>t.planId===planForm.value!.id&&t.date>=effective.value&&t.locked===undefined&&['todo','paused'].includes(t.status)&&t.pauseSource!=='user').length:0);
const remaining=computed(()=>reviewType.value==='plan'?tasks.value.filter(t=>t.planId===review.value?.id&&!['done','partial','ended'].includes(t.status)):[]);
const state=(s:string)=>({active:'进行中',paused:'已暂停',done:'已完成'}[s]??s);
async function perform(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:'保存失败，请重试';}finally{busy.value=false;}}
function editGoal(g?:Goal){error.value='';editor.value='goal';goalForm.value=g?{...g}:{id:uid(),name:'',category:'学习',criteria:'',description:'',assetId:'A11',status:'active',version:0,createdAt:Date.now()};}
function editPlan(p?:Plan,goalId?:string){error.value='';const g=goals.value.find(g=>g.id===goalId)??goals.value.find(g=>g.status==='active');if(!p&&!g){editGoal();error.value='先创建一个目标，再为它安排计划。';return;}editor.value='plan';effective.value=p?addDays(day(),1):day();planForm.value=p?{...p,weekdays:[...p.weekdays]}:{id:uid(),goalId:g!.id,name:'',taskName:'',category:g!.category,criteria:'',frequency:'daily',weekdays:[1,2,3,4,5],startDate:day(),endDate:addDays(day(),6),minutes:15,stars:1,assetId:'M11',status:'active',version:0,createdAt:Date.now()};}
function openReview(item:Goal|Plan,type:'goal'|'plan'){error.value='';review.value=item;reviewType.value=type;agreed.value=false;closeRemaining.value=false;editor.value='review';}
function selectTemplate(t:typeof templates[number]){template.value={...t};templateFrequency.value='daily';templateWeekdays.value=[1,2,3,4,5];start.value=day();end.value=addDays(day(),6);stars.value=1;editor.value='template';error.value='';}
function results(id:string){const list=tasks.value.filter(t=>t.planId===id);return `${list.filter(t=>t.status==='done').length} 件完成 · ${list.filter(t=>t.status==='partial').length} 件部分完成 · ${list.length} 件已生成`;}
onUnmounted(registerUpdateGuard(()=>busy.value||!!editor.value));
</script>

<template>
 <section class="planning-section">
  <div class="section-heading"><h2>把想法变成小计划</h2><div class="actions"><button class="secondary" @click="editGoal()">创建目标</button><button class="secondary" @click="editPlan()">创建计划</button></div></div>
  <div class="segmented planning-tabs" aria-label="目标计划内容"><button v-for="t in ['我的目标','我的计划','推荐模板']" :key="t" :class="{active:tab===t}" @click="tab=t">{{t}}</button></div>
  <p v-if="error" class="error" role="alert">{{error}}</p>
  <section v-if="editor" ref="editorElement" class="panel planning-editor">
   <div class="section-heading"><h2>{{editor==='goal'?'我的目标':editor==='plan'?'我的计划':editor==='template'?'使用这个模板':'对照标准，回顾一下'}}</h2><button class="quiet" :disabled="busy" @click="editor=''">取消</button></div>
   <form v-if="editor==='goal'&&goalForm" @submit.prevent="perform(async()=>{await saveGoal(goalForm!,goalForm!.version);editor='';tab='我的目标';emit('notice','目标已保存，可以为它制定计划啦')})">
    <label>我想做到什么<input v-model="goalForm.name" required maxlength="40" placeholder="比如：读懂一本喜欢的书"></label><label>做到什么就算达成<textarea v-model="goalForm.criteria" required maxlength="200"></textarea></label>
    <div class="two-col"><label>方向<select v-model="goalForm.category"><option v-for="c in categories" :key="c">{{c}}</option></select></label><label>希望哪天做到（可选）<input :value="goalForm.dueDate" type="date" @input="goalForm.dueDate=($event.target as HTMLInputElement).value||undefined"></label></div><label>我的想法（可选）<textarea v-model="goalForm.description" maxlength="500"></textarea></label>
    <details><summary>选择达成后的成就图案</summary><div class="award-picker"><label v-for="n in 20" :key="n"><input v-model="goalForm.assetId" type="radio" :value="'A'+String(n).padStart(2,'0')" name="achievement"><img :src="'./assets/A'+String(n).padStart(2,'0')+'.webp'" :alt="'成就图案'+n"></label></div></details>
    <button class="primary wide" :disabled="busy">保存目标</button>
   </form>
   <form v-if="editor==='plan'&&planForm" @submit.prevent="perform(async()=>{const r=await savePlan(planForm!,planForm!.version,effective);editor='';tab='我的计划';emit('notice',`计划已保存，更新 ${r.updated} 项，新增 ${r.generated} 项任务`)})">
    <label>属于哪个目标<select v-model="planForm.goalId" required :disabled="planForm.version>0"><option v-for="g in goals.filter(g=>g.status==='active'||g.id===planForm?.goalId)" :key="g.id" :value="g.id">{{g.name}}</option></select></label>
    <label>计划叫什么<input v-model="planForm.name" required maxlength="40" placeholder="比如：每天读一小段"></label><label>每次要做的任务<input v-model="planForm.taskName" required maxlength="40"></label><label>每次做到什么就算完成<textarea v-model="planForm.criteria" required maxlength="200"></textarea></label>
    <div class="two-col"><label>从哪天开始<input v-model="planForm.startDate" type="date" required></label><label>安排到哪天<input v-model="planForm.endDate" type="date" :min="planForm.startDate" required></label></div>
    <label>多久做一次<select v-model="planForm.frequency"><option value="daily">每天</option><option value="weekly">每周指定星期</option><option value="once">只做一次</option></select></label>
    <fieldset v-if="planForm.frequency==='weekly'" class="weekdays"><legend>选择星期</legend><label v-for="(w,i) in ['日','一','二','三','四','五','六']" :key="i"><input v-model="planForm.weekdays" type="checkbox" :value="i">周{{w}}</label></fieldset>
    <div class="two-col"><label>预计用时（分钟）<input v-model.number="planForm.minutes" type="number" min="1" max="60" step="1" required></label><label>每次任务星星<input v-model.number="planForm.stars" type="number" min="0" max="99" step="1" required></label></div>
    <details><summary>选择完成计划后的勋章图案</summary><div class="award-picker"><label v-for="n in 20" :key="n"><input v-model="planForm.assetId" type="radio" :value="'M'+String(n).padStart(2,'0')" name="medal"><img :src="'./assets/M'+String(n).padStart(2,'0')+'.webp'" :alt="'勋章图案'+n"></label></div></details>
    <div v-if="planForm.version>0" class="criteria"><label>修改从哪天生效<input v-model="effective" required type="date" :min="day()"></label><p>将影响 {{affected}} 项尚未开始的安排。已开始任务和单独设置的星星保留原值。</p></div>
    <div class="criteria"><strong>未来7天的安排预览</strong><p>{{preview.length?preview.join('、'):'这个窗口内没有安排；到日期后再生成。'}}</p></div>
    <button class="primary wide" :disabled="busy">保存计划</button>
   </form>
   <form v-if="editor==='template'" @submit.prevent="perform(async()=>{const count=await useTemplate(template.id,start,end,stars,{...template,frequency:templateFrequency,weekdays:templateWeekdays});editor='';tab='我的计划';emit('notice',`已创建目标和计划，生成 ${count} 项任务`)})">
    <label>我的目标<input v-model="template.name" required maxlength="40"></label><label>目标完成标准<textarea v-model="template.goalCriteria" required maxlength="200"></textarea></label><label>每次的任务<input v-model="template.taskName" required maxlength="38"></label><label>每次任务完成标准<textarea v-model="template.criteria" required maxlength="200"></textarea></label>
    <div class="two-col"><label>开始日期<input v-model="start" type="date" required></label><label>结束日期<input v-model="end" type="date" required :min="start"></label></div>
    <label>多久做一次<select v-model="templateFrequency"><option value="daily">每天</option><option value="weekly">每周指定星期</option><option value="once">只做一次</option></select></label><fieldset v-if="templateFrequency==='weekly'" class="weekdays"><legend>选择星期</legend><label v-for="(w,i) in ['日','一','二','三','四','五','六']" :key="i"><input v-model="templateWeekdays" type="checkbox" :value="i">周{{w}}</label></fieldset>
    <div class="two-col"><label>预计用时（分钟）<input v-model.number="template.minutes" type="number" min="1" max="60" required></label><label>每次任务星星<input v-model.number="stars" type="number" min="0" max="99" required></label></div><div class="criteria"><strong>未来7天的安排预览</strong><p>{{templatePreview.length?templatePreview.join('、'):'这个窗口内没有安排；到日期后再生成。'}}</p></div><p class="small muted">保存为自己的目标和计划；原模板保持不变。</p><button class="primary wide" :disabled="busy">使用这个安排</button>
   </form>
   <form v-if="editor==='review'&&review" @submit.prevent="perform(async()=>{if(!agreed)throw Error('请先对照完成标准确认');if(reviewType==='plan')await completePlan(review!.id,review!.version,closeRemaining);else await completeGoal(review!.id,review!.version);editor='';emit('notice',reviewType==='plan'?'计划完成，勋章已经收好啦':'目标达成，成就已经收好啦')})"><h3>{{review.name}}</h3><p class="criteria">{{review.criteria}}</p><p v-if="reviewType==='plan'">{{results(review.id)}}</p><div v-if="remaining.length"><p>还有 {{remaining.length}} 项未结束的安排：</p><ul><li v-for="t in remaining" :key="t.id">{{t.name}} · {{t.date}} {{t.locked!==undefined?'（已经开始，请先记录结果）':''}}</li></ul><label class="checkbox-row"><input v-model="closeRemaining" type="checkbox">结束以上尚未开始的安排，保留已有记录</label></div><p v-if="reviewType==='goal'" class="muted">关联计划需要逐项回顾完成；目标不会自动按任务比例达成。</p><label class="checkbox-row"><input v-model="agreed" type="checkbox" required>我已经对照标准，确认达成了</label><button class="primary wide" :disabled="busy||!agreed">确认{{reviewType==='plan'?'完成计划':'达成目标'}}</button></form>
  </section>
  <div v-if="tab==='我的目标'" class="arrangements"><article v-for="g in filteredGoals" :key="g.id" class="panel arrangement"><div class="meta"><span>{{g.category}}</span><span>{{state(g.status)}}</span></div><h3>{{g.name}}</h3><p>{{g.criteria}}</p><small v-if="g.dueDate">希望完成日期：{{g.dueDate}}</small><div v-if="g.status!=='done'" class="plan-actions"><button :disabled="busy" @click="editGoal(g)">编辑</button><button :disabled="busy||g.status!=='active'" @click="editPlan(undefined,g.id)">制定计划</button><button :disabled="busy" @click="perform(async()=>{await setGoalPaused(g.id,g.status==='active');emit('notice','目标与关联安排状态已更新')})">{{g.status==='active'?'暂停目标':'恢复目标'}}</button><button class="secondary" @click="openReview(g,'goal')">回顾目标</button></div><p v-else class="muted">已达成 · {{day(g.completedAt)}}</p><details><summary>关联计划 {{plans.filter(p=>p.goalId===g.id).length}} 项</summary><p v-for="p in plans.filter(p=>p.goalId===g.id)" :key="p.id">{{p.name}} · {{state(p.status)}}</p></details></article><p v-if="!filteredGoals.length" class="muted">还没有这个方向的目标，可以自己创建，也可以选一个模板。</p></div>
  <div v-if="tab==='我的计划'" class="arrangements"><article v-for="p in filteredPlans" :key="p.id" class="panel arrangement"><div class="meta"><span>{{p.category}}</span><span>{{state(p.status)}}</span></div><h3>{{p.name}}</h3><small>目标：{{goals.find(g=>g.id===p.goalId)?.name}}</small><p>{{p.criteria}}</p><small>{{p.startDate}} — {{p.endDate}}</small><p class="small">{{results(p.id)}}</p><div v-if="p.status!=='done'" class="plan-actions"><button @click="editPlan(p)">编辑计划</button><button :disabled="busy" @click="perform(async()=>{await setPlanPaused(p.id,p.status==='active');emit('notice','计划状态已更新')})">{{p.status==='active'?'暂停计划':'恢复计划'}}</button><button class="secondary" @click="openReview(p,'plan')">回顾并完成</button></div><p v-else class="muted">已完成 · {{day(p.completedAt)}}</p><details><summary>查看已生成任务</summary><div v-for="t in tasks.filter(t=>t.planId===p.id)" :key="t.id" class="record-row"><span>{{t.name}}<small>{{t.date}} · {{({todo:'待完成',started:'已开始',done:'完成',partial:'部分完成',paused:'暂停',ended:'已结束'})[t.status]}}</small></span><span class="stars">★ {{t.locked??t.stars}}</span></div></details></article><p v-if="!filteredPlans.length" class="muted">为目标制定计划，每天就知道要做哪件事。</p></div>
  <div v-if="tab==='推荐模板'" class="arrangements"><article v-for="t in templates.filter(t=>category==='全部'||t.category===category)" :key="t.id" class="panel arrangement template-card"><div><img class="template-art" :src="'./assets/A'+t.asset+'.webp'" alt="达成目标后的成就图案"><span class="tag">{{t.category}}</span></div><h3>{{t.name}}</h3><p>{{t.goalCriteria}}</p><small>每天 · {{t.minutes}} 分钟</small><button class="secondary wide" @click="selectTemplate(t)">看看这个安排</button></article></div>
 </section>
</template>
