<script setup lang="ts">
import { ref,computed,onUnmounted,watch,nextTick } from 'vue';
import { liveQuery } from 'dexie';
import { db,uid,day,type Ledger } from './data';
import { type Prize,type Redemption,type RewardImage,imageUrl } from './reward-model';
import { savePrize,redeemPrize,approveRedemption,claimRedemption,cancelRedemption,prepareRewardImage,PrizeChangedError,rewardReport } from './rewards';
import { registerUpdateGuard } from './update-safety';
const props=defineProps<{from:string;to:string;parent:boolean}>();
const emit=defineEmits<{back:[];notice:[message:string]}>();
const tab=ref('可兑换'),prizes=ref<Prize[]>([]),orders=ref<Redemption[]>([]),images=ref<RewardImage[]>([]),ledger=ref<Ledger[]>([]),busy=ref(false),error=ref(''),editor=ref<Prize>(),newImage=ref<RewardImage>(),confirmation=ref<Prize>(),requestId=ref(''),action=ref<{order:Redemption;kind:'claim'|'cancel'|'approve'}>(),status=ref('全部'),all=ref(true),fulfillment=ref(''),cancelReason=ref('');
const removeGuard=registerUpdateGuard(()=>busy.value||!!editor.value||!!confirmation.value||!!action.value);onUnmounted(removeGuard);
const sub=liveQuery(async()=>({prizes:await db.prizes.toArray(),orders:await db.redemptions.toArray(),images:await db.rewardImages.toArray(),ledger:await db.ledger.toArray()})).subscribe({next:d=>{prizes.value=d.prizes;orders.value=d.orders;images.value=d.images;ledger.value=d.ledger;},error:e=>error.value=String(e)});onUnmounted(()=>sub.unsubscribe());
const report=computed(()=>rewardReport(ledger.value,orders.value,props.from,props.to));
const records=computed(()=>orders.value.filter(o=>(all.value||(day(o.redeemedAt)>=props.from&&day(o.redeemedAt)<=props.to))&&(status.value==='全部'||o.status===status.value)).sort((a,b)=>b.redeemedAt-a.redeemedAt));
const picture=(id?:string)=>imageUrl(images.value.find(i=>i.id===id));
const labels={requested:'等家长确认',pending:'已确认 · 待兑现',claimed:'已领取',cancelled:'已取消'};
watch([editor,confirmation,action],async()=>{await nextTick();const panel=document.querySelector<HTMLElement>('.rewards-page .reward-confirm,.rewards-page form.panel');if(panel){panel.scrollIntoView({block:'start'});panel.querySelector<HTMLElement>('input,button')?.focus({preventScroll:true});}});
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=e instanceof Error?e.message:'保存失败，请重试';}finally{busy.value=false;}}
function edit(p?:Prize){if(!props.parent)return;error.value='';newImage.value=undefined;editor.value=p?{...p}:{id:uid(),name:'',description:'',costStars:10,enabled:true,version:0,createdAt:Date.now(),updatedAt:Date.now()};}
async function upload(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(file)await run(async()=>{newImage.value=await prepareRewardImage(file);});input.value='';}
async function redeem(){await run(async()=>{const p=confirmation.value!;try{await redeemPrize(p.id,p.version,requestId.value);confirmation.value=undefined;emit('notice','申请已提交，星星已预留，等家长确认');tab.value='兑换记录';all.value=true;}catch(e){if(e instanceof PrizeChangedError)confirmation.value=await db.prizes.get(p.id);throw e;}});}
</script>
<template>
 <main class="rewards-page"><button class="quiet" @click="emit('back')">‹ 返回我的成长</button>
 <section class="page-heading"><div><div class="eyebrow">让努力变成小小的期待</div><h1>我的奖励</h1><p class="muted">{{orders.filter(o=>o.status==='requested').length}} 份申请等家长确认 · {{orders.filter(o=>o.status==='pending').length}} 份礼品等待兑现</p></div><img class="reward-heading-art" src="./assets/gift-default.webp" alt=""><div class="balance"><span>当前可用星星</span><strong><img class="gold-star" src="./assets/icons/gold-star.svg" alt="星星"> {{report.balance}}</strong></div></section>
 <p v-if="error" class="error" role="alert">{{error}}</p>
 <div class="segmented"><button v-for="name in (parent?['可兑换','兑换记录','奖品设置']:['可兑换','兑换记录'])" :key="name" :class="{active:tab===name}" :disabled="busy||!!editor||!!confirmation||!!action" @click="tab=name">{{name}}</button></div>
 <section v-if="confirmation" class="panel reward-confirm" aria-label="确认兑换"><h2>预留 {{confirmation.costStars}} 颗星星，申请兑换？</h2><h3>{{confirmation.name}}</h3><p>{{confirmation.description}}</p><p>申请后先预留星星，家长确认后约定兑现时间；取消后退回预留星星。</p><div class="actions"><button class="primary" :disabled="busy" @click="redeem">提交申请</button><button class="secondary" :disabled="busy" @click="confirmation=undefined">再想想</button></div></section>
 <section v-if="action" class="panel reward-confirm"><h2>{{action.kind==='approve'?'和孩子约定兑现时间':action.kind==='claim'?'已经收到礼品了吗？':'取消这次兑换？'}}</h2><p>{{action.order.nameSnapshot}} · <img class="gold-star" src="./assets/icons/gold-star.svg" alt="星星"> {{action.order.costSnapshot}}</p><p>{{action.kind==='approve'?'确认只用于安排兑现，请遵守已经约定的奖励规则。':action.kind==='claim'?'记录兑现后不能取消，请实际收到礼品后再确认。':'取消后，原来预留的星星会退回余额。'}}</p><label v-if="action.kind==='approve'">兑现时间或约定<input v-model="fulfillment" maxlength="100" placeholder="例如：周六下午一起去公园"></label><label v-if="action.kind==='cancel'&&parent">取消原因<input v-model="cancelReason" maxlength="200" placeholder="告诉孩子原因，并退回星星"></label><div class="actions"><button class="primary" :disabled="busy" @click="run(async()=>{const a=action!;await (a.kind==='approve'?approveRedemption(a.order.id,fulfillment):a.kind==='claim'?claimRedemption(a.order.id):cancelRedemption(a.order.id,parent?cancelReason:'孩子取消申请'));action=undefined;emit('notice','记录已保存')})">{{action.kind==='approve'?'确认并保存约定':action.kind==='claim'?'确认已兑现':'确认取消并退星'}}</button><button class="secondary" :disabled="busy" @click="action=undefined">返回</button></div></section>
 <form v-if="editor&&parent" class="panel" @submit.prevent="run(async()=>{await savePrize(editor!,editor!.version,newImage);editor=undefined;newImage=undefined;emit('notice','礼品已保存')})"><h2>{{editor.version?'编辑礼品':'添加礼品'}}</h2><label>礼品名称<input v-model="editor.name" maxlength="40" required></label><label>礼品说明<textarea v-model="editor.description" maxlength="500" placeholder="比如：周末一起去公园野餐"></textarea></label><label>需要多少颗星星<input v-model.number="editor.costStars" type="number" min="1" max="9999" step="1" required></label><div class="reward-image-editor"><img :src="newImage?imageUrl(newImage):picture(editor.imageId)" alt="礼品图片预览"><label class="file-button secondary">选择图片<input type="file" accept="image/jpeg,image/png,image/webp" :disabled="busy" @change="upload"></label><button type="button" class="quiet" :disabled="busy" @click="newImage=undefined;editor.imageId=undefined">使用默认图片</button></div><p class="small muted">JPEG、PNG 或 WebP，原图不超过 5MB。图片会自动缩小，随备份一起保存。</p><label class="checkbox-row"><input v-model="editor.enabled" type="checkbox">开放兑换</label><p class="small muted">修改礼品不会改变以前的兑换记录。</p><div class="actions"><button class="primary" :disabled="busy">保存礼品</button><button type="button" class="secondary" :disabled="busy" @click="editor=undefined">取消编辑</button></div></form>
 <template v-if="tab==='可兑换'"><div class="reward-grid"><article v-for="p in prizes.filter(p=>p.enabled)" :key="p.id" class="panel reward-card"><img :src="picture(p.imageId)" :alt="p.name"><h2>{{p.name}}</h2><p>{{p.description}}</p><strong class="stars"><img class="gold-star" src="./assets/icons/gold-star.svg" alt="星星"> {{p.costStars}}</strong><button class="primary wide" :disabled="busy||!!confirmation||report.balance<p.costStars" @click="confirmation={...p};requestId=uid();error=''">{{report.balance<p.costStars?'还差 '+(p.costStars-report.balance)+' 颗星星':'申请兑换'}}</button></article></div><section v-if="!prizes.some(p=>p.enabled)" class="panel empty"><img class="empty-art" src="./assets/gift-default.webp" alt=""><h2>给自己一个小期待</h2><p>添加一份喜欢的礼品，或一次想体验的活动。</p><p v-if="!parent">和家长商量一份小期待，再请家长添加。</p><button v-if="parent" class="primary" @click="tab='奖品设置';edit()">添加第一份礼品</button></section></template>
 <template v-if="tab==='奖品设置'&&!editor&&parent"><div class="section-heading"><h2>我的礼品清单</h2><button class="primary" @click="edit()">添加礼品</button></div><article v-for="p in prizes" :key="p.id" class="panel record-row"><div><strong>{{p.name}}</strong><small><img class="gold-star" src="./assets/icons/gold-star.svg" alt="星星"> {{p.costStars}} · {{p.enabled?'开放兑换':'已停用'}}</small></div><button class="secondary" @click="edit(p)">编辑礼品</button></article><p v-if="!prizes.length" class="empty muted">还没有礼品，添加一份小期待吧。</p></template>
 <template v-if="tab==='兑换记录'"><section class="panel"><h2>区间星星收支</h2><p class="small muted">{{from==='0000-01-01'?'全部时间':from+' — '+to}} · 沿用成长页的时间范围</p><div class="reward-totals"><span>任务获得 <strong>+{{report.earned}}</strong></span><span>申请预留 <strong>{{report.spent}}</strong></span><span>取消退回 <strong>{{report.refunded}}</strong></span><span>净预留及支出 <strong>{{report.net}}</strong></span><span>领取礼品 <strong>{{report.claimed}} 份</strong></span></div><p class="small muted">收支按实际发生时间统计，领取按领取时间统计。</p></section><div class="report-controls"><label>当前状态<select v-model="status"><option value="全部">全部状态</option><option value="requested">等家长确认</option><option value="pending">已确认 · 待兑现</option><option value="claimed">已领取</option><option value="cancelled">已取消</option></select></label><label class="checkbox-row"><input v-model="all" type="checkbox">查看全部时间的兑换</label></div><p class="small muted">列表按兑换时间筛选，显示当前领取状态。</p><article v-for="o in records" :key="o.id" class="panel reward-order"><img :src="picture(o.imageIdSnapshot)" alt=""><div><h2>{{o.nameSnapshot}}</h2><p>{{o.descriptionSnapshot}}</p><span class="tag">{{labels[o.status]}}</span><p class="small muted">{{day(o.redeemedAt)}} 兑换 · <img class="gold-star" src="./assets/icons/gold-star.svg" alt="星星"> {{o.costSnapshot}}<template v-if="o.claimedAt"> · {{day(o.claimedAt)}} 领取</template><template v-if="o.cancelledAt"> · {{day(o.cancelledAt)}} 已退回 {{o.costSnapshot}} 颗星星</template></p><p v-if="o.fulfillmentNote" class="criteria">兑现约定：{{o.fulfillmentNote}}</p><p v-if="o.cancelReason">取消原因：{{o.cancelReason}}</p><div class="actions"><button v-if="parent&&o.status==='requested'" class="primary" :disabled="busy||!!action" @click="fulfillment='';action={order:o,kind:'approve'}">确认申请</button><button v-if="parent&&o.status==='pending'" class="primary" :disabled="busy||!!action" @click="action={order:o,kind:'claim'}">记录兑现</button><button v-if="o.status==='requested'||parent&&o.status==='pending'" class="quiet" :disabled="busy||!!action" @click="cancelReason='';action={order:o,kind:'cancel'}">{{o.status==='requested'?'取消申请':'取消并退星'}}</button></div></div></article><p v-if="!records.length" class="panel empty muted">这个范围里还没有兑换记录。</p></template>
 </main>
</template>
<style>
.reward-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:24px}.reward-card{display:flex;flex-direction:column;gap:12px;min-width:0}.reward-card>img{width:100%;height:150px;object-fit:contain}.reward-card h2,.reward-card p{margin:0;overflow-wrap:anywhere}.reward-card p{flex:1;color:var(--muted)}.reward-card button{margin-top:8px}.reward-confirm{border:2px solid #6b9470;margin-top:20px}.reward-image-editor{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.reward-image-editor>img,.reward-order>img{width:96px;height:96px;object-fit:contain}.reward-order{display:flex;gap:20px}.reward-order>div{min-width:0;overflow-wrap:anywhere}.reward-totals{display:flex;flex-wrap:wrap;gap:24px}.reward-totals span{display:grid;gap:8px}.reward-totals strong{font-size:24px}@media(max-width:650px){.reward-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.reward-card{padding:14px}.reward-card>img{height:110px}.reward-order>img{width:64px;height:64px}.reward-order{gap:12px}.reward-card button{padding:10px 4px;font-size:13px}}
</style>
