import 'fake-indexeddb/auto';
import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import { db,ForestDB,saveTask,completeTask,moveToday,exportBackup,restoreBackup,validateBackup,day,uid,type Task } from '../src/data';
import { saveGoal,savePlan,generateTasks,setPlanPaused,setGoalPaused,setTaskPaused,completePlan,completeGoal,selectCompanion,settleDays,useTemplate,addDays,templates } from '../src/progression';
import { type Goal,type Plan } from '../src/progression-model';
import Dexie from 'dexie';
const goal=(id='g'):Goal=>({id,name:'读懂故事',category:'学习',criteria:'分享故事情节',description:'',assetId:'A11',status:'active',version:1,createdAt:Date.now()});
const plan=(id='p',goalId='g'):Plan=>({id,goalId,name:'每日阅读',taskName:'阅读一段',category:'学习',criteria:'说说喜欢的情节',frequency:'daily',weekdays:[],startDate:day(),endDate:addDays(day(),10),minutes:15,stars:3,assetId:'M11',status:'active',version:1,createdAt:Date.now()});
const task=(id:string):Task=>({id,name:'小事',category:'习惯',criteria:'完成小事',date:day(),stars:0,minutes:5,status:'todo',createdAt:Date.now()});
beforeEach(async()=>{for(const t of db.tables)await t.clear();});
afterEach(()=>vi.restoreAllMocks());
async function seed(){await saveGoal(goal());await savePlan(plan());}
describe('计划生成与更新',()=>{
 it('使用新建表单的初始版本0保存，数据库统一写入版本1',async()=>{await saveGoal({...goal(),version:0},0);await savePlan({...plan(),version:0},0);expect((await db.goals.get('g'))?.version).toBe(1);expect((await db.plans.get('p'))?.version).toBe(1);expect(await db.tasks.count()).toBe(7);});
 it('未来生效的频率修改不能提前生成今天任务，后续补齐仍遵守原规则',async()=>{await saveGoal(goal());const weekday=new Date(day()+'T00:00:00Z').getUTCDay();await savePlan({...plan(),frequency:'weekly',weekdays:[(weekday+1)%7]});expect(await db.tasks.where('date').equals(day()).count()).toBe(0);await savePlan({...plan(),frequency:'daily'},1,addDays(day(),1));await generateTasks();expect(await db.tasks.where('date').equals(day()).count()).toBe(0);expect(await db.tasks.count()).toBe(6);});
 it('模板保存前可修改标准和频率，不覆盖内置模板',async()=>{const original=templates[0].name;await useTemplate('reading-v1',day(),addDays(day(),6),0,{name:'我选的书',goalCriteria:'讲出故事',taskName:'读两页',criteria:'能说出主角',minutes:10,frequency:'once',weekdays:[]});expect((await db.goals.toArray())[0].name).toBe('我选的书');expect((await db.tasks.toArray())[0].criteria).toBe('能说出主角');expect(await db.tasks.count()).toBe(1);expect(templates[0].name).toBe(original);});
 it('模板一次事务创建目标计划和7天任务，重复补齐不增发',async()=>{expect(await useTemplate('reading-v1',day(),addDays(day(),10),3)).toBe(7);expect(await generateTasks()).toBe(0);expect(await db.goals.count()).toBe(1);expect(await db.plans.count()).toBe(1);expect(await db.tasks.count()).toBe(7);});
 it('按每日/每周/单次生成，未来窗口之外不会预先发任务',async()=>{await saveGoal(goal());await savePlan({...plan(),frequency:'once'});expect(await db.tasks.count()).toBe(1);await savePlan({...plan('weekly'),frequency:'weekly',weekdays:[1,3]});expect(await db.tasks.where('planId').equals('weekly').count()).toBe(2);await savePlan({...plan('future'),startDate:addDays(day(),20),endDate:addDays(day(),30)});expect(await db.tasks.where('planId').equals('future').count()).toBe(0);});
 it('未来任务改期沿用ID和发生日，不重新生成；滚动不补过去',async()=>{await seed();const next=(await db.tasks.where('date').equals(addDays(day(),1)).first())!;await moveToday(next.id);await generateTasks();expect(await db.tasks.count()).toBe(7);expect((await db.tasks.get(next.id))?.occurrenceDate).toBe(next.occurrenceDate);await generateTasks(addDays(day(),20));expect(await db.tasks.count()).toBe(7);});
 it('计划改星只更新生效后的未开始任务，单项覆盖与锁定不变',async()=>{await seed();const tasks=await db.tasks.orderBy('date').toArray();await saveTask({...tasks[1],stars:5});await db.tasks.update(tasks[2].id,{status:'started',locked:3});await savePlan({...plan(),stars:8},1,addDays(day(),1));expect((await db.tasks.get(tasks[0].id))?.stars).toBe(3);expect((await db.tasks.get(tasks[1].id))?.stars).toBe(5);expect((await db.tasks.get(tasks[2].id))?.stars).toBe(3);expect((await db.tasks.get(tasks[3].id))?.stars).toBe(8);});
 it('暂停恢复不会恢复学生自行暂停的任务和独立暂停计划',async()=>{await seed();const t=(await db.tasks.toArray())[0];await setTaskPaused(t.id,true);await setPlanPaused('p',true);expect(await generateTasks()).toBe(0);await setPlanPaused('p',false);expect((await db.tasks.get(t.id))?.status).toBe('paused');await setPlanPaused('p',true);await setGoalPaused('g',true);await setGoalPaused('g',false);expect((await db.plans.get('p'))?.status).toBe('paused');});
 it('每周无星期校验失败，不产生半份计划',async()=>{await saveGoal(goal());await expect(savePlan({...plan(),frequency:'weekly',weekdays:[]})).rejects.toThrow();expect(await db.plans.count()).toBe(0);expect(await db.tasks.count()).toBe(0);});
});
describe('回顾与收藏',()=>{
 it('开始过的任务必须处理，确认结束未开始任务后才授勋',async()=>{await seed();const t=(await db.tasks.toArray())[0];await db.tasks.update(t.id,{status:'started',locked:3});await expect(completePlan('p',1,true)).rejects.toThrow('开始过');await completeTask(t.id,'partial');await expect(completePlan('p',1,false)).rejects.toThrow('确认结束');await completePlan('p',1,true);await completePlan('p',1,true);expect(await db.awards.count()).toBe(1);expect(await db.ledger.count()).toBe(0);expect(await generateTasks()).toBe(0);});
 it('目标与计划各自回顾，来源幂等，备份恢复不重发收藏',async()=>{await seed();await expect(completeGoal('g',1)).rejects.toThrow('关联计划');await completePlan('p',1,true);await completeGoal('g',1);await completeGoal('g',1);expect(await db.awards.count()).toBe(2);const b=await exportBackup();await restoreBackup(b);expect(await db.awards.count()).toBe(2);expect(validateBackup(await exportBackup()).goals[0].status).toBe('done');});
});
describe('伙伴成长',()=>{
 it('首次完成锁定当日伙伴，更换不影响日结，零星也计开心日',async()=>{await db.profiles.add({id:'student',nickname:'小禾',grade:'一年级',companion:'tuantuan',reduceMotion:false});for(let n=0;n<4;n++){await saveTask(task('t'+n));await completeTask('t'+n,'done');if(n===0)await selectCompanion('taotao');}await settleDays(addDays(day(),1));await settleDays(addDays(day(),1));expect((await db.journeys.where('companionId').equals('tuantuan').first())?.total).toBe(1);expect((await db.journeys.where('companionId').equals('taotao').first())?.total).toBe(0);expect(await db.settlements.count()).toBe(1);});
 it('三阶段分别10/20/30，60日完成仅一颗成长之星，新旅程保留历史',async()=>{await db.profiles.add({id:'student',nickname:'小禾',grade:'一年级',companion:'tuantuan',reduceMotion:false});let at=Date.parse('2026-01-01T10:00:00+08:00');vi.spyOn(Date,'now').mockImplementation(()=>at);for(let n=0;n<60;n++){at=Date.parse(addDays('2026-01-01',n)+'T10:00:00+08:00');for(let k=0;k<4;k++){await saveTask(task(`${n}-${k}`));await completeTask(`${n}-${k}`,'done');}await settleDays(addDays(day(),1));const j=(await db.journeys.toArray())[0];if(n===9)expect([j.stage,j.points]).toEqual([2,0]);if(n===29)expect([j.stage,j.points]).toEqual([3,0]);}expect((await db.journeys.toArray())[0].total).toBe(60);expect(await db.awards.count()).toBe(1);await settleDays(addDays(day(),1));expect(await db.awards.count()).toBe(1);await selectCompanion('tuantuan');expect(await db.journeys.count()).toBe(1);await selectCompanion('tuantuan',true);expect(await db.journeys.count()).toBe(2);expect(validateBackup(await exportBackup()).journeys.length).toBe(2);});
});
describe('版本兼容',()=>{
 it('0.1备份转入0.2，保留原任务与奖励',async()=>{await saveTask(task('old'));await completeTask('old','done');const b=await exportBackup();const old={schemaVersion:1,appVersion:'0.1.0',exportedAt:b.exportedAt,profiles:b.profiles,tasks:b.tasks,sessions:b.sessions,segments:b.segments,ledger:b.ledger,orders:b.orders};await restoreBackup(old);expect(await db.tasks.count()).toBe(1);expect(await db.ledger.count()).toBe(1);expect(await db.goals.count()).toBe(0);});
 it('旧IndexedDB升级保留数据并增加新表',async()=>{const name='migration-'+uid();const old=new Dexie(name);old.version(1).stores({profiles:'id',tasks:'id,date,status',sessions:'id,status,taskId',segments:'id,sessionId,date',ledger:'key,taskId',orders:'date'});await old.table('tasks').add(task('persist'));old.close();const upgraded=new ForestDB(name);try{expect((await upgraded.tasks.get('persist'))?.name).toBe('小事');expect(await upgraded.goals.count()).toBe(0);}finally{await upgraded.delete();}});
 it('不接受缺少新增表的v2备份与坏引用',async()=>{await seed();const b=await exportBackup();expect(()=>validateBackup({...b,goals:undefined})).toThrow();expect(()=>validateBackup({...b,goals:[]})).toThrow('关联');});
 it('不接受丢失或改错的收藏',async()=>{await seed();await completePlan('p',1,true);const b=await exportBackup();expect(()=>validateBackup({...b,awards:[]})).toThrow('缺少勋章');expect(()=>validateBackup({...b,awards:b.awards.map(a=>({...a,assetId:'M01'}))})).toThrow('来源');});
});
